- name: Create the namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ ootnamespace }}"
    kubeconfig: "{{ kubeconfig }}"
    state: present

- name: Build the source container image
  shell:
    "podman build -t {{ registry }}/{{ sourcecontainer }}:latest -f Dockerfile.source {{ repopath }}/src-container"

- name: Push the source container image
  shell:
    "podman push --authfile={{ pull_secret }} --tls-verify=false {{ registry }}/{{ sourcecontainer }}:latest"

- name: Add the Helm chart as a ConfigMap
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  shell:
    "oc -n {{ ootnamespace }} create cm charts --from-file={{ repopath }}/charts/index.yaml --from-file={{ repopath }}/charts/ice-driver-0.0.1.tgz"

